[package]
name = "pdfluent-examples"
version = "0.1.0"
edition = "2021"
publish = false

[[example]]
name = "text_extraction"

[[example]]
name = "form_fill"

[[example]]
name = "merge_pdfs"

[[example]]
name = "pdfa_validate"

[[example]]
name = "redact_text"

[[example]]
name = "howto_compress_pdf"

[[example]]
name = "howto_encrypt_pdf"

[[example]]
name = "howto_extract_text_by_page"

[[example]]
name = "howto_extract_text_pdf"

[[example]]
name = "howto_read_pdf_metadata"

[[example]]
name = "howto_write_pdf_metadata"

[[example]]
name = "howto_generate_pdf_thumbnails"

[[example]]
name = "howto_get_pdf_page_count"

[[example]]
name = "howto_merge_pdfs"

[[example]]
name = "howto_render_pdf_to_jpeg"

[[example]]
name = "howto_render_pdf_to_png"

[[example]]
name = "howto_open_pdf_with_password"

[[example]]
name = "howto_fill_pdf_form"

[dependencies]
pdfluent = { version = "1.0.0", features = ["signing", "pdfa", "redaction"] }
